---
AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'app/**/*.rb'
  Exclude:
    - '_*/**/*'

# ignore block length in non-production code
Metrics/BlockLength:
  Enabled: true
  Max: 40
  Exclude:
    - spec/**/*
    - Rakefile

# allow unsafe YAML loading in non-production code
Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile
    - app/infrastructure/database/migrations/*.rb

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Enabled: true
  Max: 90
  Exclude:
    - Rakefile
