---
development:
  PHQ_TOKEN: <personal access token for github api> 
  PHQ_CLIENT_ID: <personal access token for github api> 
  PHQ_SECRET_KEY: <personal access token for github api> 
  REDISCLOUD_URL: <set by Heroku provisioned Redis>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  GET_INFO_QUEUE: codepraise-clone-development
  GET_INFO_QUEUE_URL: <set by AWS>

test:
  PHQ_TOKEN: <personal access token for github api> 
  PHQ_CLIENT_ID: <personal access token for github api> 
  PHQ_SECRET_KEY: <personal access token for github api> 
  REDISCLOUD_URL: <set by Heroku provisioned Redis>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  GET_INFO_QUEUE: codepraise-clone-development
  GET_INFO_QUEUE_URL: <set by AWS>


production:
  PHQ_TOKEN: <personal access token for github api> 
  PHQ_CLIENT_ID: <personal access token for github api> 
  PHQ_SECRET_KEY: <personal access token for github api> 
  REDISCLOUD_URL: <set by Heroku provisioned Redis>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  GET_INFO_QUEUE: codepraise-clone-development
  GET_INFO_QUEUE_URL: <set by AWS>
